---
name: Build

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run on push on main branch
        run: |
          echo "Hello artifactory-cleanup on main!"
      - name: Run on push on pull request
        if: github.event_name == 'pull_request'
        run: |
          echo "Hello artifactory-cleanup in pull request!"
